server:
  port: 8092
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: BorrowGroup,ReturnGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: OrderNotification:com.example.notification.kafka.OrderNotification


    mail:
    host: localhost
    port: 1025
    username: Laila Timasli
    password: lailaensa
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000


